### ISSUE TITLE
Rotate block rotates beds in a wrong way

### ISSUE THREAD

**Issue by zlainsama** [McJty/interactionwheel#3]
Versions: intwheel-1.1x-1.1.1
Pictures: [Imgur Link](http://imgur.com/a/O35PY)
I didn't test on doors, large chests and other rotatable multi-block.

by the way, curse project page doesn't have a issues button/link to here.

**Comment by McJty** [comment]
This is actually a bug in Forge. The rotateBlock implementation as added by forge doesn't properly work with these kinds of vanilla blocks. So not much I can do about it in my mod except a hardcoded check but I'd rather that forge solves this.

I'll add an issue link
