### ISSUE TITLE
Binding to mouse buttons causes delays & crashes

### ISSUE THREAD

**Issue by NekoAmps** [McJty/interactionwheel#4]
When the user binds the "Open the Interaction Wheel" control to a mouse button (Button 1, Button 2, or Button 3) and then uses the assigned button on a block, the wheel doesn't appear until the user presses a keyboard key. If the user presses a keyboard key again while the wheel is up, the game crashes.

Interaction Wheel version: 1.2.1
Forge version: 13.20.0.2226
Minecraft version: 1.11.2
Additional mods: CompatLayer 0.1.7

And here's [the most recent crash log](https://github.com/McJty/interactionwheel/files/737343/crash-2017-01-28_22.29.04-client.txt).

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Will be fixed next release

**Comment by NekoAmps** [comment]
Thank you for attending to this up so quickly! 😸
