### ISSUE TITLE
Compatibility with Applied Energistics

### ISSUE THREAD

**Issue by Xiaminou** [McJty/interactionwheel#6]
When Interaction Wheel is present Applied Energistics' "shortcuts" such as picking up 1 item with shift+right-clicking and then a second one, or middle-mouse-button to craft an item, do not work.

**Comment by McJty** [comment]
Can you clarify? You mean when the wheel is open? Or what?

**Comment by Xiaminou** [comment]
No, I mean the mod is present.

**Comment by McJty** [comment]
I don't see how that can be a bug with Interaction Wheel as I don't catch any keys. The wheel is just a gui which acts to keys only when it is open

**Comment by Xiaminou** [comment]
I couldn't tell you, but I've confirmed it by testing with just Interaction Wheel and Applied Energistics.

**Comment by McJty** [comment]
What is the keybinding for the wheel set too?

**Comment by Xiaminou** [comment]
Hmmm, I may have rushed to judgement because it's not happening anymore. That's weird.

Now I'm questioning if I didn't derp up my testing.

Okay well, I don't know what I messed up but it's not your mod that's causing the problem.
